<!DOCTYPE html>
<html lang="en-us" itemscope itemtype="http://schema.org/WebPage">
  <head>
  <title>Google Sign in Error 403 in Open edX</title>
  
  <meta http-equiv="cache-control" content="public, max-age=31536000" />
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="Faizar Septiawan">
  <meta name="description" content="Catch your problem solution or read interesting stories on my blog! | Palugada paling ganteng di Makassar | #Cyclist Enthusiast | Palugada paling gila di Makassar | Read - Search - Ask | Sekali Gila Tetap Gila">
  <meta name="keywords" content="Activities, Android Developer, Ansible, Apache2, Atlassian, Ayo Belajar Linux, Bestpath Network, BLC Telkom Klaten, BSD, Caddy Server, Case Study, Cisco, Cisco Indonesia, Cloud Computing, Cockpit, Custom Weapons, Docker, E-Learning, Engenius, Error, FreeBSD, FreeBSD Indonesia, Komunitas Pengguna Linux Indonesia, KPLI Bulukumba, KPLI Klaten, Lets Encrypt, Linux, MacOS, Microsoft Azure, Microsoft SQL Server, MikroTik, MikroTik Indonesia, MySQL, Nginx, Open edX, OpenSID, Others, PHP, phpMyAdmin, PostgreSQL, Proxmox, Python, Redash, Sendy, SSH, Stories, Subnetting, TP-Link, Ubiquiti, Unix, Virtualization, Windows, X-Mosque, Faizar Septiawan, Icar, siBunglonGanteng, Orang Ganteng, siBunglonLabs, Programmer, SysAdmin, Site Reliability Engineer, Developer, Palugada, Makassar, Ganteng, Gila, Cyclist">

  <!-- Open Graph data -->
  <meta property="og:title" content="Google Sign in Error 403 in Open edX" />
<meta property="og:description" content="When I have configuration OAuth2 Google on Open edX version ironwood.master, I click register, then the “Google” login button and I get to the Google Log In page. After a succesful login on Google site, it redirects to my site and I’m getting error. When check the file /edx/var/log/lms/edx.log i find this:
Jul 24 01:03:09 bnpb [service_variant=lms][django.request][env:sandbox] ERROR [e-Learning 29535] [exception.py:135] - Internal Server Error: /auth/complete/google-oauth2/ Traceback (most recent call last): File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://sibunglon.com/2020/07/26/google-sign-in-error-403-in-open-edx/" /><meta property="og:image" content="https://sibunglon.com/assets/img/profil-cycling-4.jpg"/><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2020-07-26T20:43:08+08:00" />
<meta property="article:modified_time" content="2020-07-26T20:43:08+08:00" /><meta property="og:site_name" content="The Official Site of siBunglon" />


  <!-- schema data -->
  <meta itemprop="name" content="Google Sign in Error 403 in Open edX">
<meta itemprop="description" content="When I have configuration OAuth2 Google on Open edX version ironwood.master, I click register, then the “Google” login button and I get to the Google Log In page. After a succesful login on Google site, it redirects to my site and I’m getting error. When check the file /edx/var/log/lms/edx.log i find this:
Jul 24 01:03:09 bnpb [service_variant=lms][django.request][env:sandbox] ERROR [e-Learning 29535] [exception.py:135] - Internal Server Error: /auth/complete/google-oauth2/ Traceback (most recent call last): File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2."><meta itemprop="datePublished" content="2020-07-26T20:43:08+08:00" />
<meta itemprop="dateModified" content="2020-07-26T20:43:08+08:00" />
<meta itemprop="wordCount" content="291"><meta itemprop="image" content="https://sibunglon.com/assets/img/profil-cycling-4.jpg"/>
<meta itemprop="keywords" content="Open edX," />

  <!-- Twitter cards data -->
  <meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:image" content="https://sibunglon.com/assets/img/profil-cycling-4.jpg"/>

<meta name="twitter:title" content="Google Sign in Error 403 in Open edX"/>
<meta name="twitter:description" content="When I have configuration OAuth2 Google on Open edX version ironwood.master, I click register, then the “Google” login button and I get to the Google Log In page. After a succesful login on Google site, it redirects to my site and I’m getting error. When check the file /edx/var/log/lms/edx.log i find this:
Jul 24 01:03:09 bnpb [service_variant=lms][django.request][env:sandbox] ERROR [e-Learning 29535] [exception.py:135] - Internal Server Error: /auth/complete/google-oauth2/ Traceback (most recent call last): File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2."/>

  

  
  <meta name="google-site-verification" content="SYE8MCa03gDSATy55M-WppXlauxSYqxjOE9Tg7vEJpM" />
  
  
  
  
  
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-L0K35LHNTF"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-L0K35LHNTF');
  </script>
  
  

  
  
  
  
  
  <link rel="stylesheet" href="/assets/css/external.min.css" media="screen">
  
  
  <link rel="stylesheet" href="/assets/css/styles.css" media="screen">
  <link src="/assets/custom/googlefonts/roboto.css" rel="stylesheet">
  

  
  
  
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/src/images/apple-touch-icon.png">
  <link rel="shortcut icon" href="/src/images/favicon.ico">
  

  
  <!-- RSS -->
  <link href="/posts/index.xml" rel="alternate" type="application/rss+xml" title="Faizar Septiawan - Palugada paling ganteng di Makassar" />
  

  
  
  <script defer src="/assets/custom/fontawesome-5.15.1/js/all.min.js"></script>
  
  
</head>

  <body>
    
      <nav>
  <a href="/">
    siBunglon
  </a>
  <a href="/posts">
    Posts
  </a>
</nav>

    
    <main class="container">
      
  <article>
    <header>
      <small>
        <span class="date">July 26, 2020</span></small>
      <h1>Google Sign in Error 403 in Open edX</h1>
    </header>
    <section><p><img src="/assets/img/Open-edX/open-edx-new.png" alt="Activities, Android Developer, Ansible, Apache2, Atlassian, Ayo Belajar Linux, Bestpath Network, BLC Telkom Klaten, BSD, Caddy Server, Case Study, Cisco, Cisco Indonesia, Cloud Computing, Cockpit, Custom Weapons, Docker, E-Learning, Engenius, Error, FreeBSD, FreeBSD Indonesia, Komunitas Pengguna Linux Indonesia, KPLI Bulukumba, KPLI Klaten, Lets Encrypt, Linux, MacOS, Microsoft Azure, Microsoft SQL Server, MikroTik, MikroTik Indonesia, MySQL, Nginx, Open edX, OpenSID, Others, PHP, phpMyAdmin, PostgreSQL, Proxmox, Python, Redash, Sendy, SSH, Stories, Subnetting, TP-Link, Ubiquiti, Unix, Virtualization, Windows, X-Mosque, Faizar Septiawan, Icar, siBunglonGanteng, Orang Ganteng, siBunglonLabs, Programmer, SysAdmin, Site Reliability Engineer, Developer, Palugada, Makassar, Ganteng, Gila, Cyclist"></p>
<p>When I have configuration OAuth2 Google on Open edX version ironwood.master, I click register, then the “Google” login button and I get to the Google Log In page. After a succesful login on Google site, it redirects to my site and I’m getting error. When check the file <code>/edx/var/log/lms/edx.log</code> i find this:</p>
<pre tabindex="0"><code class="language-log" data-lang="log">Jul 24 01:03:09 bnpb [service_variant=lms][django.request][env:sandbox] ERROR [e-Learning  29535] [exception.py:135] - Internal Server Error: /auth/complete/google-oauth2/
Traceback (most recent call last):
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/exception.py&#34;, line 41, in inner
    response = get_response(request)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 249, in _legacy_get_response
    response = self._get_response(request)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py&#34;, line 185, in inner
    return func(*args, **kwargs)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/decorators/cache.py&#34;, line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/views/decorators/csrf.py&#34;, line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/social_django/utils.py&#34;, line 49, in wrapper
    return func(request, backend, *args, **kwargs)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/social_django/views.py&#34;, line 33, in complete
    *args, **kwargs)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/social_core/actions.py&#34;, line 41, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/social_core/backends/base.py&#34;, line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/social_core/utils.py&#34;, line 252, in wrapper
    return func(*args, **kwargs)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/social_core/backends/oauth.py&#34;, line 405, in auth_complete
    *args, **kwargs)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/social_core/utils.py&#34;, line 252, in wrapper
    return func(*args, **kwargs)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/social_core/backends/oauth.py&#34;, line 410, in do_auth
    data = self.user_data(access_token, *args, **kwargs)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/social_core/backends/google.py&#34;, line 59, in user_data
    &#39;alt&#39;: &#39;json&#39;
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/social_core/backends/base.py&#34;, line 238, in get_json
    return self.request(url, *args, **kwargs).json()
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/social_core/backends/base.py&#34;, line 234, in request
    response.raise_for_status()
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/requests/models.py&#34;, line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: Forbidden for url: https://www.googleapis.com/plus/v1/people/me?access_token=xxxx.xxxxxx&amp;alt=json
</code></pre><p><em>Google Sign In Error 403</em> because deprecated Google+ API. For fix this issue, need upgrade the package versions to <code>social-auth-app-django==3.1.0</code> and <code>social-auth-core==3.2.0</code> using command:</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-bash" data-lang="bash"><span class="line"><span class="cl">$ sudo /edx/bin/pip.edxapp install social-auth-app-django<span class="o">==</span>3.1.0 social-auth-core<span class="o">==</span>3.2.0
</span></span></code></pre></div><h3 id="references">References</h3>
<ul>
<li><a href="https://discuss.openedx.org/t/google-sign-in-error-403-deprecated-google-api/965">Open edX discussions</a></li>
</ul>
</section>
    <footer>
      <hr>
      <div class="meta">
        <p class="tags">
          
            
              <a href="/tags/open-edx">
                <span>#</span>Open edX</a>
            
          
        </p>
      </div>
      <hr>
      <div id="disqus_thread"></div>
<script type="application/javascript">
    window.disqus_config = function () {
    
    
    
    };
    (function() {
        if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
            document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
            return;
        }
        var d = document, s = d.createElement('script'); s.async = true;
        s.src = '//' + "sibunglonlabs" + '.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    </footer>
  </article>

    </main>
    
      <footer>
  <p>
    &copy; 2023 Faizar Septiawan. <a href="http://creativecommons.org/licenses/by-sa/4.0/">Some Rights Reserved</a>.
  </p>
  <p>
    Powered by <a href="https://gohugo.io" title="A Fast and Flexible Website Generator">Hugo</a> &amp; <a href="https://github.com/eshlox/simplicity" title="Hugo theme">Simplicity</a>.
  </p>
</footer>

    
    
    
    
    
    
    
    <script src="/assets/js/scripts.min.js"></script>
    
      
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'G-L0K35LHNTF', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>

    
  </body>
</html>
