<!DOCTYPE html>
<html lang="en-us" itemscope itemtype="http://schema.org/WebPage">
  <head>
  <title>Database returned an invalid value in QuerySet.datetimes()</title>
  
  <meta http-equiv="cache-control" content="public, max-age=31536000" />
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="Faizar Septiawan">
  <meta name="description" content="Read - Search - Ask | Personal Site | Catch your problem solution or read interesting stories on my blog!">
  <meta name="keywords" content="Activities, Android Developer, Ansible, Apache2, Atlassian, Ayo Belajar Linux, Bestpath Network, BLC Telkom Klaten, BSD, Caddy Server, Case Study, Cisco, Cisco Indonesia, Cloud Computing, Cockpit, Custom Weapons, Docker, E-Learning, Engenius, Error, FreeBSD, FreeBSD Indonesia, Komunitas Pengguna Linux Indonesia, KPLI Bulukumba, KPLI Klaten, Let&#39;s Encrypt, Linux, MacOS, Microsoft Azure, Microsoft SQL Server, MikroTik, MikroTik Indonesia, MySQL, Nginx, Open edX, OpenSID, Others, PHP, phpMyAdmin, PostgreSQL, Proxmox, Python, Redash, Sendy, SSH, Stories, Subnetting, TP-Link, Ubiquiti, Unix, Virtualization, Windows, X-Mosque, Faizar Septiawan, Icar, siBunglonGanteng, Orang Ganteng, siBunglonLabs">
  
  
  
  <meta name="google-site-verification" content="SYE8MCa03gDSATy55M-WppXlauxSYqxjOE9Tg7vEJpM" />
  
  
  
  
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-110194945-3"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-110194945-3');
  </script>
  
  

  
  
  
  
  
  <link rel="stylesheet" href="/assets/css/external.min.css" media="screen">
  
  
  <link rel="stylesheet" href="/assets/css/styles.css" media="screen">
  <link src="/assets/custom/googlefonts/roboto.css" rel="stylesheet">
  

  
  
  
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/src/images/apple-touch-icon.png">
  <link rel="shortcut icon" href="/src/images/favicon.ico">
  

  
  <link href="/posts/index.xml" rel="alternate" type="application/rss+xml" title="The Official Site of siBunglon" />

  <meta property="og:title" content="Database returned an invalid value in QuerySet.datetimes()" />
<meta property="og:description" content="After create new action on the Django admin pages, it redirects to my site with the message a server error. When check the file /edx/var/log/supervisor/lms-stderr.log i find this:
Traceback (most recent call last): File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/exception.py&#34;, line 41, in inner response = get_response(request) File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 249, in _legacy_get_response response = self._get_response(request) File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 217, in _get_response response = self.process_exception_by_middleware(e, request) File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 215, in _get_response response = response." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://sibunglon.com/2020/07/26/database-returned-an-invalid-value-in-queryset.datetimes/" /><meta property="og:image" content="https://sibunglon.com/assets/img/profil.webp"/><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2020-07-26T21:05:49+08:00" />
<meta property="article:modified_time" content="2020-07-26T21:05:49+08:00" /><meta property="og:site_name" content="The Official Site of siBunglon" />


  <meta itemprop="name" content="Database returned an invalid value in QuerySet.datetimes()">
<meta itemprop="description" content="After create new action on the Django admin pages, it redirects to my site with the message a server error. When check the file /edx/var/log/supervisor/lms-stderr.log i find this:
Traceback (most recent call last): File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/exception.py&#34;, line 41, in inner response = get_response(request) File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 249, in _legacy_get_response response = self._get_response(request) File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 217, in _get_response response = self.process_exception_by_middleware(e, request) File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 215, in _get_response response = response."><meta itemprop="datePublished" content="2020-07-26T21:05:49+08:00" />
<meta itemprop="dateModified" content="2020-07-26T21:05:49+08:00" />
<meta itemprop="wordCount" content="393"><meta itemprop="image" content="https://sibunglon.com/assets/img/profil.webp"/>
<meta itemprop="keywords" content="Ayo Belajar Linux,MySQL,Open edX,Error," />
  <meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:image" content="https://sibunglon.com/assets/img/profil.webp"/>

<meta name="twitter:title" content="Database returned an invalid value in QuerySet.datetimes()"/>
<meta name="twitter:description" content="After create new action on the Django admin pages, it redirects to my site with the message a server error. When check the file /edx/var/log/supervisor/lms-stderr.log i find this:
Traceback (most recent call last): File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/exception.py&#34;, line 41, in inner response = get_response(request) File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 249, in _legacy_get_response response = self._get_response(request) File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 217, in _get_response response = self.process_exception_by_middleware(e, request) File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 215, in _get_response response = response."/>

  

  
  
  <script defer src="/assets/custom/fontawesome-5.15.1/js/all.min.js"></script>
  
  
</head>

  <body>
    
      <nav>
  <a href="/">
    siBunglon
  </a>
  <a href="/posts">
    Posts
  </a>
</nav>

    
    <main class="container">
      
  <article>
    <header>
      <small>
        <span class="date">July 26, 2020</span></small>
      <h1>Database returned an invalid value in QuerySet.datetimes()</h1>
    </header>
    <section><p><img src="/assets/img/Open-edX/open-edx-new.png" alt="Activities, Android Developer, Ansible, Apache2, Atlassian, Ayo Belajar Linux, Bestpath Network, BLC Telkom Klaten, BSD, Caddy Server, Case Study, Cisco, Cisco Indonesia, Cloud Computing, Cockpit, Custom Weapons, Docker, E-Learning, Engenius, Error, FreeBSD, FreeBSD Indonesia, Komunitas Pengguna Linux Indonesia, KPLI Bulukumba, KPLI Klaten, Let&#39;s Encrypt, Linux, MacOS, Microsoft Azure, Microsoft SQL Server, MikroTik, MikroTik Indonesia, MySQL, Nginx, Open edX, OpenSID, Others, PHP, phpMyAdmin, PostgreSQL, Proxmox, Python, Redash, Sendy, SSH, Stories, Subnetting, TP-Link, Ubiquiti, Unix, Virtualization, Windows, X-Mosque, Faizar Septiawan, Icar, siBunglonGanteng, Orang Ganteng, siBunglonLabs"></p>
<p>After create new action on the Django admin pages, it redirects to my site with the message a server error. When check the file <code>/edx/var/log/supervisor/lms-stderr.log</code> i find this:</p>
<pre tabindex="0"><code class="language-log" data-lang="log">Traceback (most recent call last):
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/exception.py&#34;, line 41, in inner
    response = get_response(request)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 249, in _legacy_get_response
    response = self._get_response(request)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py&#34;, line 215, in _get_response
    response = response.render()
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/response.py&#34;, line 107, in render
    self.content = self.rendered_content
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/response.py&#34;, line 84, in rendered_content
    content = template.render(context, self._request)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/backends/django.py&#34;, line 66, in render
    return self.template.render(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py&#34;, line 207, in render
    return self._render(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py&#34;, line 199, in _render
    return self.nodelist.render(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py&#34;, line 990, in render
    bit = node.render_annotated(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py&#34;, line 957, in render_annotated
    return self.render(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/loader_tags.py&#34;, line 177, in render
    return compiled_parent._render(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py&#34;, line 199, in _render
    return self.nodelist.render(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py&#34;, line 990, in render
    bit = node.render_annotated(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py&#34;, line 957, in render_annotated
    return self.render(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/loader_tags.py&#34;, line 177, in render
    return compiled_parent._render(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py&#34;, line 199, in _render
    return self.nodelist.render(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py&#34;, line 990, in render
    bit = node.render_annotated(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py&#34;, line 957, in render_annotated
    return self.render(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/loader_tags.py&#34;, line 72, in render
    result = block.nodelist.render(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py&#34;, line 990, in render
    bit = node.render_annotated(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py&#34;, line 957, in render_annotated
    return self.render(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/loader_tags.py&#34;, line 72, in render
    result = block.nodelist.render(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py&#34;, line 990, in render
    bit = node.render_annotated(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/base.py&#34;, line 957, in render_annotated
    return self.render(context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/library.py&#34;, line 225, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_list.py&#34;, line 418, in date_hierarchy
    } for year in years]
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py&#34;, line 250, in __iter__
    self._fetch_all()
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py&#34;, line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/query.py&#34;, line 152, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch):
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py&#34;, line 847, in results_iter
    row = self.apply_converters(row, converters)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py&#34;, line 832, in apply_converters
    value = converter(value, expression, self.connection, self.query.context)
  File &#34;/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/functions/datetime.py&#34;, line 198, in convert_value
    &#34;Database returned an invalid datetime value. &#34;
ValueError: Database returned an invalid datetime value. Are time zone definitions for your database installed?
</code></pre><h3 id="how-to-fix-this-issues">How to fix this issues?</h3>
<p>The MySQL database has tables of timezone information that seems to be missing. You can re-populate the database with:</p>
<div class="highlight"><pre tabindex="0" class="chroma"><code class="language-bash" data-lang="bash"><span class="line"><span class="cl">$ mysql_tzinfo_to_sql /usr/share/zoneinfo <span class="p">|</span> sed -e <span class="s2">&#34;s/Local time zone must be set--see zic manual page/local/&#34;</span> <span class="p">|</span> mysql -u root mysql
</span></span></code></pre></div><h3 id="references">References</h3>
<ul>
<li><a href="https://openedx.atlassian.net/wiki/spaces/OXA/pages/187662621/Database+returned+an+invalid+value+in+QuerySet.datetimes">Open edX Confluence</a></li>
</ul>
</section>
    <footer>
      <hr>
      <div class="meta">
        <p class="tags">
          
            
              <a href="/tags/ayo-belajar-linux">
                <span>#</span>Ayo Belajar Linux</a>
            
              <a href="/tags/mysql">
                <span>#</span>MySQL</a>
            
              <a href="/tags/open-edx">
                <span>#</span>Open edX</a>
            
              <a href="/tags/error">
                <span>#</span>Error</a>
            
          
        </p>
      </div>
      <hr>
      <div id="disqus_thread"></div>
<script type="application/javascript">
    window.disqus_config = function () {
    
    
    
    };
    (function() {
        if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
            document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
            return;
        }
        var d = document, s = d.createElement('script'); s.async = true;
        s.src = '//' + "sibunglonlabs" + '.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    </footer>
  </article>

    </main>
    
      <footer>
  <p>
    &copy; 2022 Faizar Septiawan. <a href="http://creativecommons.org/licenses/by-sa/4.0/">Some Rights Reserved</a>.
  </p>
  <p>
    Powered by <a href="https://gohugo.io" title="A Fast and Flexible Website Generator">Hugo</a> &amp; <a href="https://github.com/eshlox/simplicity" title="Hugo theme">Simplicity</a>.
  </p>
</footer>

    
    
    
    
    
    
    
    <script src="/assets/js/scripts.min.js"></script>
    
      
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'UA-110194945-3', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>

    
  </body>
</html>
