<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Python on Faizar Septiawan - Palugada paling ganteng di Makassar</title>
    <link>https://sibunglon.com/tags/python/</link>
    <description>Recent content in Python on Faizar Septiawan - Palugada paling ganteng di Makassar</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Mon, 30 Dec 2019 21:45:42 +0700</lastBuildDate>
    
      <atom:link href="https://sibunglon.com/tags/python/index.xml" rel="self" type="application/rss+xml" />
    
    
      <item>
        <title>Disable SSL Certificate Verification on Script Python</title>
        <link>https://sibunglon.com/2019/12/30/disable-ssl-certificate-verification-on-script-python/</link>
        <pubDate>Mon, 30 Dec 2019 21:45:42 +0700</pubDate>
        <guid>https://sibunglon.com/2019/12/30/disable-ssl-certificate-verification-on-script-python/</guid>
        <description>&lt;p&gt;I failed to run a telegram bot in another environment, more or less the error as follows.&lt;/p&gt;
&lt;div class=&#34;highlight&#34;&gt;&lt;pre tabindex=&#34;0&#34; class=&#34;chroma&#34;&gt;&lt;code class=&#34;language-bash&#34; data-lang=&#34;bash&#34;&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;urllib3.exceptions.MaxRetryError: HTTPSConnectionPool&lt;span class=&#34;o&#34;&gt;(&lt;/span&gt;&lt;span class=&#34;nv&#34;&gt;host&lt;/span&gt;&lt;span class=&#34;o&#34;&gt;=&lt;/span&gt;&lt;span class=&#34;s1&#34;&gt;&amp;#39;api.telegram.org&amp;#39;&lt;/span&gt;, &lt;span class=&#34;nv&#34;&gt;port&lt;/span&gt;&lt;span class=&#34;o&#34;&gt;=&lt;/span&gt;443&lt;span class=&#34;o&#34;&gt;)&lt;/span&gt;: Max retries exceeded with url  &lt;span class=&#34;o&#34;&gt;(&lt;/span&gt;Caused by SSLError&lt;span class=&#34;o&#34;&gt;(&lt;/span&gt;SSLError&lt;span class=&#34;o&#34;&gt;(&lt;/span&gt;1, u&lt;span class=&#34;s1&#34;&gt;&amp;#39;[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)&amp;#39;&lt;/span&gt;&lt;span class=&#34;o&#34;&gt;)&lt;/span&gt;,&lt;span class=&#34;o&#34;&gt;))&lt;/span&gt;
&lt;/span&gt;&lt;/span&gt;&lt;/code&gt;&lt;/pre&gt;&lt;/div&gt;&lt;p&gt;But after adding the following script, my bot finally managed to run in that environment. Maybe someone has a case related to SSL certificate verification, hopefully the following script can help.&lt;/p&gt;
&lt;div class=&#34;highlight&#34;&gt;&lt;pre tabindex=&#34;0&#34; class=&#34;chroma&#34;&gt;&lt;code class=&#34;language-python&#34; data-lang=&#34;python&#34;&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;&lt;span class=&#34;ch&#34;&gt;#!/bin/python&lt;/span&gt;
&lt;/span&gt;&lt;/span&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;&lt;span class=&#34;kn&#34;&gt;import&lt;/span&gt; &lt;span class=&#34;nn&#34;&gt;ssl&lt;/span&gt;
&lt;/span&gt;&lt;/span&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;
&lt;/span&gt;&lt;/span&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;&lt;span class=&#34;k&#34;&gt;try&lt;/span&gt;&lt;span class=&#34;p&#34;&gt;:&lt;/span&gt;
&lt;/span&gt;&lt;/span&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;    &lt;span class=&#34;n&#34;&gt;_create_unverified_https_context&lt;/span&gt; &lt;span class=&#34;o&#34;&gt;=&lt;/span&gt; &lt;span class=&#34;n&#34;&gt;ssl&lt;/span&gt;&lt;span class=&#34;o&#34;&gt;.&lt;/span&gt;&lt;span class=&#34;n&#34;&gt;_create_unverified_context&lt;/span&gt;
&lt;/span&gt;&lt;/span&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;&lt;span class=&#34;k&#34;&gt;except&lt;/span&gt; &lt;span class=&#34;ne&#34;&gt;AttributeError&lt;/span&gt;&lt;span class=&#34;p&#34;&gt;:&lt;/span&gt;
&lt;/span&gt;&lt;/span&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;    &lt;span class=&#34;c1&#34;&gt;# Legacy Python that doesn&amp;#39;t verify HTTPS certificates by default&lt;/span&gt;
&lt;/span&gt;&lt;/span&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;    &lt;span class=&#34;k&#34;&gt;pass&lt;/span&gt;
&lt;/span&gt;&lt;/span&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;&lt;span class=&#34;k&#34;&gt;else&lt;/span&gt;&lt;span class=&#34;p&#34;&gt;:&lt;/span&gt;
&lt;/span&gt;&lt;/span&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;    &lt;span class=&#34;c1&#34;&gt;# Handle target environment that doesn&amp;#39;t support HTTPS verification&lt;/span&gt;
&lt;/span&gt;&lt;/span&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;    &lt;span class=&#34;n&#34;&gt;ssl&lt;/span&gt;&lt;span class=&#34;o&#34;&gt;.&lt;/span&gt;&lt;span class=&#34;n&#34;&gt;_create_default_https_context&lt;/span&gt; &lt;span class=&#34;o&#34;&gt;=&lt;/span&gt; &lt;span class=&#34;n&#34;&gt;_create_unverified_https_context&lt;/span&gt;
&lt;/span&gt;&lt;/span&gt;&lt;/code&gt;&lt;/pre&gt;&lt;/div&gt;</description>
      </item>
    
      <item>
        <title>Create New Super User for Access Django Admin Interface in Open edX</title>
        <link>https://sibunglon.com/2019/07/15/create-new-super-user-for-access-django-admin-interface-in-open-edx/</link>
        <pubDate>Mon, 15 Jul 2019 03:09:25 +0700</pubDate>
        <guid>https://sibunglon.com/2019/07/15/create-new-super-user-for-access-django-admin-interface-in-open-edx/</guid>
        <description>&lt;p&gt;&lt;img src=&#34;https://sibunglon.com/assets/img/Open-edX/open-edx-new.png&#34; alt=&#34;Activities, Android Developer, Ansible, Apache2, Atlassian, Ayo Belajar Linux, Bestpath Network, BLC Telkom Klaten, BSD, Caddy Server, Case Study, Cisco, Cisco Indonesia, Cloud Computing, Cockpit, Custom Weapons, Docker, E-Learning, Engenius, Error, FreeBSD, FreeBSD Indonesia, Komunitas Pengguna Linux Indonesia, KPLI Bulukumba, KPLI Klaten, Lets Encrypt, Linux, MacOS, Microsoft Azure, Microsoft SQL Server, MikroTik, MikroTik Indonesia, MySQL, Nginx, Open edX, OpenSID, Others, PHP, phpMyAdmin, PostgreSQL, Proxmox, Python, Redash, Sendy, SSH, Stories, Subnetting, TP-Link, Ubiquiti, Unix, Virtualization, Windows, X-Mosque, Faizar Septiawan, Icar, siBunglonGanteng, Orang Ganteng, siBunglonLabs, Programmer, SysAdmin, Site Reliability Engineer, Developer, Palugada, Makassar, Ganteng, Gila, Cyclist, Panglima, Setan, Panglima Setan, sibunglon, Ganteng&#34;&gt;&lt;/p&gt;</description>
      </item>
    
      <item>
        <title>Install Package From PIP Ignore Trusted Host</title>
        <link>https://sibunglon.com/2019/02/26/install-package-from-pip-ignore-trusted-host/</link>
        <pubDate>Tue, 26 Feb 2019 10:53:16 +0700</pubDate>
        <guid>https://sibunglon.com/2019/02/26/install-package-from-pip-ignore-trusted-host/</guid>
        <description>&lt;h3 id=&#34;connection-is-power&#34;&gt;Connection is Power&lt;/h3&gt;
&lt;p&gt;Yah &lt;strong&gt;connection is power&lt;/strong&gt; dan jangan berpikir &lt;strong&gt;problems can occur due to connection&lt;/strong&gt; ketika kalian menemukan masalah yang berkaitan dengan internet. Disuatu waktu &lt;strong&gt;I&amp;rsquo;m siBunglon&lt;/strong&gt; menemukan masalah pada saat akan melakukan installasi package dari python-pip, paketnya tidak bisa diinstall tapi diwaktu itu &lt;strong&gt;I&amp;rsquo;m siBunglon&lt;/strong&gt; menggunakan koneksi yang dikelola oleh orang lain dan mencoba browsing eh ternyata lancar jaya, mencoba menggunakan Wi-Fi dari device yang lain dan masalah tersebut tidak muncul. Hmmm ada yang unik, &lt;strong&gt;I&amp;rsquo;m siBunglon&lt;/strong&gt; menemukan errors message seperti berikut:&lt;/p&gt;</description>
      </item>
    
      <item>
        <title>PIP Python2 Error</title>
        <link>https://sibunglon.com/2018/12/11/pip-python2-error/</link>
        <pubDate>Tue, 11 Dec 2018 21:34:18 +0700</pubDate>
        <guid>https://sibunglon.com/2018/12/11/pip-python2-error/</guid>
        <description>&lt;h3 id=&#34;pip-di-python2-error&#34;&gt;Pip di Python2 Error?&lt;/h3&gt;
&lt;pre tabindex=&#34;0&#34;&gt;&lt;code&gt;Traceback (most recent call last):
  File &amp;#34;/usr/bin/pip&amp;#34;, line 9, in &amp;lt;module&amp;gt;
    from pip import main
ImportError: cannot import name main
&lt;/code&gt;&lt;/pre&gt;&lt;p&gt;Gak usah panik, cukup jalankan command berikut tapi pastikan terlebih dahulu sekarang sudah jadi super user (&lt;strong&gt;root&lt;/strong&gt;)&lt;/p&gt;
&lt;pre tabindex=&#34;0&#34;&gt;&lt;code&gt;python -m pip uninstall pip &amp;amp;&amp;amp; apt install python-pip --reinstall
&lt;/code&gt;&lt;/pre&gt;</description>
      </item>
    
      <item>
        <title>Python Tidak Memiliki Objek SSL_ST_INIT</title>
        <link>https://sibunglon.com/2018/12/10/python-tidak-memiliki-objek-ssl_st_init/</link>
        <pubDate>Mon, 10 Dec 2018 23:47:30 +0700</pubDate>
        <guid>https://sibunglon.com/2018/12/10/python-tidak-memiliki-objek-ssl_st_init/</guid>
        <description>&lt;p&gt;Jika akan menghubungkan perangkat anda dengan perangkat lain menggunakan ansible namun ketemu error &lt;strong&gt;ERROR! Unexpected Exception: &amp;lsquo;module&amp;rsquo; object has no attribute &amp;lsquo;SSL_ST_INIT&amp;rsquo;&lt;/strong&gt;, sebenarnya itu hanya membutuhkan paket &lt;strong&gt;pyOpenSSL&lt;/strong&gt; yang dapat diinstall dengan command &lt;code&gt;pip install pyOpenSSL&lt;/code&gt;&lt;/p&gt;</description>
      </item>
    
  </channel>
</rss>
